workflows:
  ios_build:
    name: Build iOS IPA
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          cd ios
          pod repo update
          pod install
          cd ..
      - name: Build IPA (unsigned)
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your@email.com
