workflows:
  ios_build:
    name: Build iOS IPA
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean and update CocoaPods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod cache clean --all
          pod repo remove trunk || true
          pod setup
          pod repo update
          pod install --repo-update
          pod update Firebase/Messaging
          cd ..
      - name: Build IPA (unsigned)
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your@email.com
